### ISSUE TITLE
[FIX] 실거래 정보 거래 내역 정보 정렬 기준 변경

### ISSUE THREAD

**Issue by isayaksh** [SSAFY-11-HOME/home-backend#4]
**🔥 문제 발생 상황**
<img width="338" alt="image" src="https://github.com/SSAFY-11-HOME/home-backend/assets/85926257/91f15884-db53-4e12-a366-8c3bd90b000b">

- 실거래가 정보 리스트의 값이 오름차순으로 정렬되어 제공되고 있다.
- 일반적으로, 사용자들은 가장 최신 거래 내역을 원하기 때문에 내림차순으로 정렬된 정보가 필요하다.

**🙏 요청 사항**
```
[ GET ] {{server}}/house/apt?id={id} 
```
- 해당 API의 `dealList`의 요소를 `dealDate` 값을 기준으로 내림차순으로 정렬되도록 수정해주세욥!

**Comment by clintkslee** [comment]
단일 주택에서의 거래정보에 대해 내림차순 정렬해서 수정했습니다.
