### ISSUE TITLE
[ 🙏 요청 ] 

### ISSUE THREAD

**Issue by isayaksh** [SSAFY-11-HOME/home-backend#5]
## 🔥 현재 상황

- 현재 검색 키워드를 이용한 검색 결과는 다음과 같다.

![image](https://github.com/SSAFY-11-HOME/home-backend/assets/85926257/b7990204-7a3e-4736-956d-75b2767c9f84)

- `용산` 이라는 키워드(`serachWord`)로 API를 요청할 경우 클라이언트에서 받는 Response는 다음과 같다.

### [ GET ] {{server}}/search/{searchWord}

```json
{
    "searchApt": [
        {
            "id": "11680000000001",
            "name": "브라운스톤역삼"
        },
        {
            "id": "11680000000007",
            "name": "역삼래미안"
        },
        {
            "id": "11680000000010",
            "name": "역삼I'PARK"
        },
        {
            "id": "11680000000011",
            "name": "역삼동하나빌"
        },
        ...
    ],
    "searchArea": [
        {
            "id": "1168010100",
            "name": "서울특별시 강남구 역삼동"
        }
    ]
}
```
### 🎨 아파트 리스트 UI
- Response의 `searchApt`의 결과로 `[ { id: String, name: String }, ... ]` 형식의 데이터를 받아 UI를 그릴 수 있다.
![image](https://github.com/SSAFY-11-HOME/home-backend/assets/85926257/5697ed17-2019-4592-8d65-f4bd6fcd88df)

- 리스트의 원소를 클릭했을 때, 카카오 지도에서 해당 건물의 위치로 이동하려면 좌표(`lat, lng`) 정보가 필요하다.
- `aptCode`에 해당하는 house 정보를 조회할 때, 해당 데이터의 좌표 값을 얻을 수 있는 방법은 없다.

## 💡 요청
- 따라서,  `aptCode`로 좌표(`lat, lng`) 정보를 포함한 house 정보를 조회하는 API를 추가하거나, 조회 기능을 담당하는 API의 Response를 수정을 요청합니다

**Comment by clintkslee** [comment]
https://apis.map.kakao.com/web/sample/addr2coord/
주소로 좌표 검색결과를 표시하는 예시 코드 입니다.
